/*
* IBM Confidential
*
* OCO Source Materials
*
* WLP Copyright IBM Corp. 2018
*
* The source code for this program is not published or otherwise divested
* of its trade secrets, irrespective of what has been deposited with the
* U.S. Copyright Office.
*/
package com.ibm.ws.cache.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 *
 */
@WebService(name = "CounterService1", targetNamespace = "http://webservices.cache.ws.ibm.com")
@XmlSeeAlso({
              ObjectFactory.class
})
public interface CounterService1 {

    /**
     *
     * @param in
     * @return
     *         returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "reset1Return", targetNamespace = "http://webservices.cache.ws.ibm.com")
    @RequestWrapper(localName = "reset1", targetNamespace = "http://webservices.cache.ws.ibm.com", className = "com.ibm.ws.cache.webservices.Reset1")
    @ResponseWrapper(localName = "reset1Response", targetNamespace = "http://webservices.cache.ws.ibm.com", className = "com.ibm.ws.cache.webservices.Reset1Response")
    public String reset1(
                         @WebParam(name = "in", targetNamespace = "http://webservices.cache.ws.ibm.com") String in);

    /**
     *
     * @param in
     * @return
     *         returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "counter1Return", targetNamespace = "http://webservices.cache.ws.ibm.com")
    @RequestWrapper(localName = "counter1", targetNamespace = "http://webservices.cache.ws.ibm.com", className = "com.ibm.ws.cache.webservices.Counter1")
    @ResponseWrapper(localName = "counter1Response", targetNamespace = "http://webservices.cache.ws.ibm.com", className = "com.ibm.ws.cache.webservices.Counter1Response")
    public String counter1(
                           @WebParam(name = "in", targetNamespace = "http://webservices.cache.ws.ibm.com") String in);

    /**
     *
     * @param in
     * @return
     *         returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "reset2Return", targetNamespace = "http://webservices.cache.ws.ibm.com")
    @RequestWrapper(localName = "reset2", targetNamespace = "http://webservices.cache.ws.ibm.com", className = "com.ibm.ws.cache.webservices.Reset2")
    @ResponseWrapper(localName = "reset2Response", targetNamespace = "http://webservices.cache.ws.ibm.com", className = "com.ibm.ws.cache.webservices.Reset2Response")
    public String reset2(
                         @WebParam(name = "in", targetNamespace = "http://webservices.cache.ws.ibm.com") String in);

    /**
     *
     * @param in
     * @return
     *         returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "counter2Return", targetNamespace = "http://webservices.cache.ws.ibm.com")
    @RequestWrapper(localName = "counter2", targetNamespace = "http://webservices.cache.ws.ibm.com", className = "com.ibm.ws.cache.webservices.Counter2")
    @ResponseWrapper(localName = "counter2Response", targetNamespace = "http://webservices.cache.ws.ibm.com", className = "com.ibm.ws.cache.webservices.Counter2Response")
    public String counter2(
                           @WebParam(name = "in", targetNamespace = "http://webservices.cache.ws.ibm.com") String in);

}
