/*
* IBM Confidential
*
* OCO Source Materials
*
* WLP Copyright IBM Corp. 2018
*
* The source code for this program is not published or otherwise divested
* of its trade secrets, irrespective of what has been deposited with the
* U.S. Copyright Office.
*/
package com.ibm.ws.cache.webservices;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CounterService1Service", targetNamespace = "http://webservices.cache.ws.ibm.com", wsdlLocation = "META-INF/wsdl/CounterService1.wsdl")
public class CounterService1Service extends Service {

    private final static URL COUNTERSERVICE1SERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTERSERVICE1SERVICE_EXCEPTION;
    private final static QName COUNTERSERVICE1SERVICE_QNAME = new QName("http://webservices.cache.ws.ibm.com", "CounterService1Service");

    static {
        COUNTERSERVICE1SERVICE_WSDL_LOCATION = com.ibm.ws.cache.webservices.CounterService1Service.class.getClassLoader().getResource("META-INF/wsdl/CounterService1.wsdl");
        WebServiceException e = null;
        if (COUNTERSERVICE1SERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/CounterService1.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        COUNTERSERVICE1SERVICE_EXCEPTION = e;
    }

    public CounterService1Service() {
        super(__getWsdlLocation(), COUNTERSERVICE1SERVICE_QNAME);
    }

    public CounterService1Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTERSERVICE1SERVICE_QNAME, features);
    }

    public CounterService1Service(URL wsdlLocation) {
        super(wsdlLocation, COUNTERSERVICE1SERVICE_QNAME);
    }

    public CounterService1Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTERSERVICE1SERVICE_QNAME, features);
    }

    public CounterService1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CounterService1Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *         returns CounterService1
     */
    @WebEndpoint(name = "CounterService1")
    public CounterService1 getCounterService1() {
        return super.getPort(new QName("http://webservices.cache.ws.ibm.com", "CounterService1"), CounterService1.class);
    }

    /**
     *
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their default
     *            values.
     * @return
     *         returns CounterService1
     */
    @WebEndpoint(name = "CounterService1")
    public CounterService1 getCounterService1(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.cache.ws.ibm.com", "CounterService1"), CounterService1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTERSERVICE1SERVICE_EXCEPTION != null) {
            throw COUNTERSERVICE1SERVICE_EXCEPTION;
        }
        return COUNTERSERVICE1SERVICE_WSDL_LOCATION;
    }

}
