# Properties which indicate features which cannot be run individually.
#
# The property key is the feature short name.  The property value is
# a descriptive reason for why the feature cannot be run by itself.
#
# Any feature listed in this properties file will not be run by the
# single feature tests.
#
# IBM-ShortName=Reason

# Skip jdbc-4.3: It uses a custom mechanism to enforce minimum java level.
jdbc-4.3=Uses a custom mechanism to enforce the minimum java level

# Enabling wsSecurity-1.1 to start on its own could break existing configurations.
wsSecurity-1.1=Cannot start by itself

constrainedDelegation-1.0=Requires spnego or OIDC

# TODO: This feature frequently runs into the following NPE
# FrameworkEvent ERROR Bundle:com.ibm.ws.http.whiteboard(id=106) java.lang.NullPointerException
#   at org.eclipse.equinox.http.servlet.internal.Activator.addingService(Activator.java:180)
#   at org.eclipse.equinox.http.servlet.internal.Activator.addingService(Activator.java:1)
#   at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
osgiAppConsole-1.0=Generates an NPE
httpWhiteboard-1.0=Generates an NPE

# WMQ features require a RAR location variable to be set.
# These simple tests do not have a RAR and have not set the
# location variable.
wmqMessagingClient-3.0=Requires variable 'wmqJmsClient.rar.location'
wmqJmsClient-2.0=Requires variable 'wmqJmsClient.rar.location'
wmqJmsClient-1.1=Requires variable 'wmqJmsClient.rar.location'
