# cacheSize = 1000
# enableDiskOffload = false
# diskOffloadLocation = c:\myLocation
# useListenerContext = false
# flushToDiskOnStop = false
# enableCacheReplication = true
# replicationDomain = DynaCacheCluster
# enableLockingSupport = true
# disableDependencyId = false
# disableTemplatesSupport = false
# enableNioSupport = false

cache.instance.0=services/cache/distributedmap_N1
cache.instance.0.cacheSize = 1000
cache.instance.0.enableDiskOffload = false
cache.instance.0.enableNioSupport = true
cache.instance.0.enableLockingSupport = false

cache.instance.1=services/cache/distributedmap_N2
cache.instance.1.cacheSize = 1000
cache.instance.1.enableDiskOffload = false
cache.instance.1.enableNioSupport = true
cache.instance.1.enableLockingSupport = false

cache.instance.2=services/cache/servletInstance_1
cache.instance.2.cacheSize = 3
cache.instance.2.enableDiskOffload = true
cache.instance.2.enableServletSupport = true

cache.instance.3=services/cache/servletInstance_2
cache.instance.3.cacheSize = 1000
cache.instance.3.enableDiskOffload = false
cache.instance.3.enableServletSupport = true

cache.instance.4=services/cache/servletInstance_3
cache.instance.4.cacheSize = 1000
cache.instance.4.enableDiskOffload = false
cache.instance.4.enableServletSupport = true

cache.instance.5=services/cache/servletInstance_4
cache.instance.5.cacheSize = 10
cache.instance.5.enableDiskOffload = false
cache.instance.5.enableServletSupport = true

cache.instance.6=services/cache/servletInstance_5
cache.instance.6.cacheSize = 10
cache.instance.6.enableDiskOffload = false
cache.instance.6.enableServletSupport = true

################### HTOD ENHANCEMENT TESTING #####################

# SERVLET HIGH
cache.instance.7=services/cache/htodServletInstance_3
cache.instance.7.cacheSize = 100
cache.instance.7.diskCacheSize = 500
cache.instance.7.enableDiskOffload = true
cache.instance.7.disableTemplatesSupport = false
cache.instance.7.diskCachePerformanceLevel = 3
cache.instance.7.diskCacheEvictionPolicy = 0
cache.instance.7.enableServletSupport = true

# SERVLET  CUSTOM
cache.instance.8=services/cache/htodServletInstance_2
cache.instance.8.cacheSize = 100
cache.instance.8.diskCacheSize = 500
cache.instance.8.enableDiskOffload = true
cache.instance.8.disableTemplatesSupport = false
cache.instance.8.diskCachePerformanceLevel = 2
cache.instance.8.htodDelayOffloadDepIdBuckets = 100
cache.instance.8.htodDelayOffloadTemplateBuckets = 100
cache.instance.8.htodDelayOffloadEntriesLimit = 100
cache.instance.8.enableServletSupport = true

# SERVLET  LOW
cache.instance.9=services/cache/htodServletInstance_0
cache.instance.9.cacheSize = 100
cache.instance.9.diskCacheSize = 500
cache.instance.9.enableDiskOffload = true
cache.instance.9.disableTemplatesSupport = false
cache.instance.9.diskCachePerformanceLevel = 0
cache.instance.9.enableServletSupport = true

# OBJECT HIGH
cache.instance.10=services/cache/htodObjectInstance_3
cache.instance.10.cacheSize = 100
cache.instance.10.diskCacheSize = 500
cache.instance.10.disableTemplatesSupport = false
cache.instance.10.enableDiskOffload = true
cache.instance.10.diskCachePerformanceLevel = 3
cache.instance.10.diskCacheEvictionPolicy = 0

# OBJECT CUSTOM
cache.instance.11=services/cache/htodObjectInstance_2
cache.instance.11.cacheSize = 100
cache.instance.11.diskCacheSize = 500
cache.instance.11.disableTemplatesSupport = false
cache.instance.11.enableDiskOffload = true
cache.instance.11.diskCachePerformanceLevel = 2
cache.instance.11.htodDelayOffloadDepIdBuckets = 100
cache.instance.11.htodDelayOffloadTemplateBuckets = 100
cache.instance.11.htodDelayOffloadEntriesLimit = 100

# OBJECT LOW
cache.instance.12=services/cache/htodObjectInstance_0
cache.instance.12.cacheSize = 100
cache.instance.12.diskCacheSize = 500
cache.instance.12.disableTemplatesSupport = false
cache.instance.12.enableDiskOffload = true
cache.instance.12.diskCachePerformanceLevel = 0

################### HTOD ENHANCEMENT TESTING #####################

# Dan P. - for MBeanCounterTest
cache.instance.13=services/cache/servletInstance_13
cache.instance.13.cacheSize = 3
cache.instance.13.enableDiskOffload = true
cache.instance.13.enableServletSupport = true
cache.instance.13.diskCacheSize = 20
cache.instance.13.diskCachePerformanceLevel = 3
cache.instance.13.diskCacheEvictionPolicy = 0

################### HTOD EVICTION TESTING #####################

# SERVLET EVICTION NONE
cache.instance.14=services/cache/htodServletInstance_14
cache.instance.14.cacheSize = 100
cache.instance.14.diskCacheSize = 500
cache.instance.14.enableDiskOffload = true
cache.instance.14.disableTemplatesSupport = false
cache.instance.14.diskCachePerformanceLevel = 2
cache.instance.14.htodDelayOffloadDepIdBuckets = 100
cache.instance.14.htodDelayOffloadTemplateBuckets = 100
cache.instance.14.htodDelayOffloadEntriesLimit = 100
cache.instance.14.enableServletSupport = true
cache.instance.14.diskCacheEvictionPolicy = 0

# SERVLET EVICTION RANDOM
cache.instance.15=services/cache/htodServletInstance_15
cache.instance.15.cacheSize = 100
cache.instance.15.diskCacheSize = 500
cache.instance.15.enableDiskOffload = true
cache.instance.15.disableTemplatesSupport = false
cache.instance.15.diskCachePerformanceLevel = 3
cache.instance.15.enableServletSupport = true
cache.instance.15.diskCacheEvictionPolicy = 1
cache.instance.15.diskCacheHighThreshold = 75
cache.instance.15.diskCacheLowThreshold = 55
cache.instance.15.diskCacheSizeInGB = 3

# SERVLET EVICTION SIZE
cache.instance.16=services/cache/htodServletInstance_16
cache.instance.16.cacheSize = 100
cache.instance.16.enableDiskOffload = true
cache.instance.16.disableTemplatesSupport = false
cache.instance.16.diskCachePerformanceLevel = 2
cache.instance.16.htodDelayOffloadDepIdBuckets = 100
cache.instance.16.htodDelayOffloadTemplateBuckets = 100
cache.instance.16.htodDelayOffloadEntriesLimit = 100
cache.instance.16.enableServletSupport = true
cache.instance.16.diskCacheEvictionPolicy = 2
cache.instance.16.diskCacheHighThreshold = 76
cache.instance.16.diskCacheLowThreshold = 56
cache.instance.16.diskCacheSizeInGB = 3

# OBJECT EVICTION NONE
cache.instance.17=services/cache/htodObjectInstance_17
cache.instance.17.cacheSize = 100
cache.instance.17.diskCacheSize = 500
cache.instance.17.enableDiskOffload = true
cache.instance.17.disableTemplatesSupport = false
cache.instance.17.diskCachePerformanceLevel = 2
cache.instance.17.htodDelayOffloadDepIdBuckets = 100
cache.instance.17.htodDelayOffloadTemplateBuckets = 100
cache.instance.17.htodDelayOffloadEntriesLimit = 100
cache.instance.17.enableServletSupport = false
cache.instance.17.diskCacheEvictionPolicy = 0

# OBJECT EVICTION RANDOM
cache.instance.18=services/cache/htodObjectInstance_18
cache.instance.18.cacheSize = 100
cache.instance.18.diskCacheSize = 500
cache.instance.18.enableDiskOffload = true
cache.instance.18.disableTemplatesSupport = false
cache.instance.18.diskCachePerformanceLevel = 2
cache.instance.18.htodDelayOffloadDepIdBuckets = 100
cache.instance.18.htodDelayOffloadTemplateBuckets = 100
cache.instance.18.htodDelayOffloadEntriesLimit = 100
cache.instance.18.enableServletSupport = false
cache.instance.18.diskCacheEvictionPolicy = 1
cache.instance.18.diskCacheHighThreshold = 78
cache.instance.18.diskCacheLowThreshold = 58
cache.instance.18.diskCacheSizeInGB = 3

# OBJECT EVICTION SIZE
cache.instance.19=services/cache/htodObjectInstance_19
cache.instance.19.cacheSize = 100
cache.instance.19.enableDiskOffload = true
cache.instance.19.disableTemplatesSupport = false
cache.instance.19.diskCachePerformanceLevel = 3
cache.instance.19.enableServletSupport = false
cache.instance.19.diskCacheEvictionPolicy = 2
cache.instance.19.diskCacheHighThreshold = 79
cache.instance.19.diskCacheLowThreshold = 59
cache.instance.19.diskCacheSizeInGB = 3

################### HTOD ASYNC LRU TO DISK TESTING #####################

# SERVLET lruToDiskTriggerPercent = 0
cache.instance.20=services/cache/htodServletInstance_20
cache.instance.20.cacheSize = 5000
cache.instance.20.enableDiskOffload = true
cache.instance.20.disableTemplatesSupport = false
cache.instance.20.diskCachePerformanceLevel = 3
cache.instance.20.enableServletSupport = true

# OBJECT lruToDiskTriggerPercent = 20
cache.instance.21=services/cache/htodObjectInstance_21
cache.instance.21.cacheSize = 5000
cache.instance.21.enableDiskOffload = true
cache.instance.21.diskCachePerformanceLevel = 3
cache.instance.21.enableServletSupport = false
cache.instance.21.lruToDiskTriggerPercent = 20

################### HTOD NIOMAP TESTING #####################

cache.instance.22=services/cache/htodNioMapObjectInstance_22
cache.instance.22.cacheSize = 100
cache.instance.22.enableDiskOffload = true
cache.instance.22.diskCachePerformanceLevel = 3
cache.instance.22.enableServletSupport = false
cache.instance.22.enableNioSupport = true

# SERVLET  VBC 
cache.instance.23=services/cache/vbcServletInstance_1
cache.instance.23.cacheSize = 10
cache.instance.23.enableDiskOffload = true
cache.instance.23.disableTemplatesSupport = false
cache.instance.23.diskCachePerformanceLevel = 3
cache.instance.23.enableServletSupport = true

################### COMPARE CACHES (PUSH and PUSH-PULL) TESTING #####################

cache.instance.24=services/cache/compareCachesInstance_24
cache.instance.24.cacheSize = 100
cache.instance.24.enableDiskOffload = true
cache.instance.24.enableServletSupport = false

################### HTODTest2 TESTING #####################

cache.instance.25=services/cache/htodInstance_25
cache.instance.25.cacheSize = 100
cache.instance.25.enableDiskOffload = true
cache.instance.25.disableTemplatesSupport = false
cache.instance.25.diskCachePerformanceLevel = 3
cache.instance.25.enableServletSupport = true

################### ObjectGrid TESTING #####################

#cache.instance.26=services/cache/distributedmap_OG1
#cache.instance.26.cacheProviderName = com.ibm.ws.objectgrid.dynacache.CacheProviderImpl
#cache.instance.26.cacheSize = 1000
#cache.instance.26.enableDiskOffload = false
#cache.instance.26.enableLockingSupport = false

#cache.instance.27=services/cache/distributedmap_OG2
#cache.instance.27.cacheProviderName = com.ibm.ws.objectgrid.dynacache.CacheProviderImpl
#cache.instance.27.cacheSize = 1000
#cache.instance.27.enableDiskOffload = false
#cache.instance.27.enableLockingSupport = false

#cache.instance.28=services/cache/distributedmap_OG1_IL
#cache.instance.28.cacheProviderName = com.ibm.ws.objectgrid.dynacache.CacheProviderImpl
#cache.instance.28.cacheSize = 20
#cache.instance.28.enableDiskOffload = false
#cache.instance.28.enableLockingSupport = false
#cache.instance.28.useListenerContext = false

#cache.instance.29=services/cache/distributedmap_OG2_IL
#cache.instance.29.cacheProviderName = com.ibm.ws.objectgrid.dynacache.CacheProviderImpl
#cache.instance.29.cacheSize = 50
#cache.instance.29.enableDiskOffload = false
#cache.instance.29.useListenerContext = false

#cache.instance.30=services/cache/distributedmap_OG1_AsyncIL
#cache.instance.30.cacheProviderName = com.ibm.ws.objectgrid.dynacache.CacheProviderImpl
#cache.instance.30.cacheSize = 20
#cache.instance.30.enableDiskOffload = false
#cache.instance.30.enableLockingSupport = false
#cache.instance.30.useListenerContext = true

#cache.instance.31=services/cache/distributedmap_OG2_AsyncIL
#cache.instance.31.cacheProviderName = com.ibm.ws.objectgrid.dynacache.CacheProviderImpl
#cache.instance.31.cacheSize = 50
#cache.instance.31.enableDiskOffload = false
#cache.instance.31.useListenerContext = true

#cache.instance.32=services/cache/distributedmap_OGS1
#cache.instance.32.cacheProviderName = com.ibm.ws.objectgrid.dynacache.CacheProviderImpl
#cache.instance.32.cacheSize = 10
#cache.instance.32.enableDiskOffload = false

#cache.instance.33=services/cache/distributedmap_OGS2
#cache.instance.33.cacheProviderName = com.ibm.ws.objectgrid.dynacache.CacheProviderImpl
#cache.instance.33.cacheSize = 10
#cache.instance.33.enableDiskOffload = false

################### NioMap Stress TESTING #####################
cache.instance.34=services/cache/niostress
cache.instance.34.cacheSize = 100
cache.instance.34.enableDiskOffload = true
cache.instance.34.diskCachePerformanceLevel = 3
cache.instance.34.enableServletSupport = false
cache.instance.34.enableNioSupport = true
cache.instance.34.diskCacheEvictionPolicy = 1
cache.instance.34.diskCacheHighThreshold = 90
cache.instance.34.diskCacheLowThreshold = 80
cache.instance.34.diskCacheSizeInGB = 3

################### DC_MEM_THRESHOLD_TESTING #####################

# JLLo. - for DC_Mem_Treshold
cache.instance.35=services/cache/dcmemthreshold
cache.instance.35.memoryCacheSizeInMB = 100
cache.instance.35.memoryCacheHighThreshold=70
cache.instance.35.memoryCacheLowThreshold=50
