# cacheSize = 1000
# enableDiskOffload = false
# diskOffloadLocation = c:\myLocation
# useListenerContext = false
# flushToDiskOnStop = false
# enableCacheReplication = true
# replicationDomain = DynaCacheCluster





cache.instance.0=services/cache/distributedmap_1
cache.instance.0.cacheSize = 1000
cache.instance.0.enableDiskOffload = false

cache.instance.1=services/cache/distributedmap_2
cache.instance.1.cacheSize = 1000
cache.instance.1.enableDiskOffload = false


